# Run `docker-compose build` to build an image for api and workers containers.
# Run `docker-compose up` to run all containers.

version: "3.4"

services:
  pg:
    image: postgres:latest
    restart: on-failure
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/posgresql/data

  rabbit:
    image: rabbitmq:latest
    restart: on-failure
    ports:
      - "5672:5672/tcp"
    healthcheck: #tells us if rabit is ready
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

  api:
    build:
      context: ./
      dockerfile: docker/dev-app.Dockerfile
    image: pdf_convertor_api
    restart: on-failure
    env_file: .env
    environment:
      DEBUG: 1
    depends_on:
      rabbit:
        condition: service_healthy
      pg:
        condition: service_started
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data

  worker:
    image: pdf_convertor_worker
    build:
      context: ./
      dockerfile: docker/dev-worker.Dockerfile
    env_file: .env
    restart: on-failure
    volumes:
      - ./data:/data
    depends_on:
      rabbit:
        condition: service_healthy
      pg:
        condition: service_started


volumes:
  pgdata: