# Generated by Django 4.2 on 2023-12-21 11:26

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('done', models.BooleanField(default=False)),
                ('pages', models.IntegerField(default=-1)),
            ],
        ),
    ]
